\hypertarget{classChronos_1_1Core_1_1ChronosCoreException}{}\section{Chronos.\+Core.\+Chronos\+Core\+Exception Class Reference}
\label{classChronos_1_1Core_1_1ChronosCoreException}\index{Chronos.\+Core.\+Chronos\+Core\+Exception@{Chronos.\+Core.\+Chronos\+Core\+Exception}}


An Exception indicating that Chronos has encountered an error from which it is unable to recover.  


Inheritance diagram for Chronos.\+Core.\+Chronos\+Core\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classChronos_1_1Core_1_1ChronosCoreException}
\end{center}
\end{figure}


\subsection{Detailed Description}
An Exception indicating that Chronos has encountered an error from which it is unable to recover. 

This Exception should only be thrown if the A\+PI is being used in an incorrect manner. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
Chronos/Core.\+py\end{DoxyCompactItemize}
