\hypertarget{classChronos_1_1Gateway_1_1ChronosGatewayException}{}\section{Chronos.\+Gateway.\+Chronos\+Gateway\+Exception Class Reference}
\label{classChronos_1_1Gateway_1_1ChronosGatewayException}\index{Chronos.\+Gateway.\+Chronos\+Gateway\+Exception@{Chronos.\+Gateway.\+Chronos\+Gateway\+Exception}}


An Exception indicating that Chronos has encountered an error from which it is unable to recover.  


Inheritance diagram for Chronos.\+Gateway.\+Chronos\+Gateway\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classChronos_1_1Gateway_1_1ChronosGatewayException}
\end{center}
\end{figure}


\subsection{Detailed Description}
An Exception indicating that Chronos has encountered an error from which it is unable to recover. 

This Exception could be thrown due to network events, logic errors, or inconsistent state. 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
Chronos/\hyperlink{Gateway_8py}{Gateway.\+py}\end{DoxyCompactItemize}
